Nhid:
  - 32
  - 64
  - 128
Mhid: []
inhib_layers:
  - 100
  - 100
  - 100
cls_sq_layers:
  - 100
  - 100
  - 100
alpha:
  - 0.99
alpharp:
  - 0.65
batch_size: 16
beta:
  - 0.97
betas:
  - 0.
  - 0.95
resume_from: /Users/nwang/wide_guided/run/logs/train_hybrid_vae_guided_base/default/Oct29_13-10-57_pgi15-gpu5.iff.kfa-juelich.de/test/ #an_example_model/checkpoints # resume from latest checkpoint of the specified model logfile. If you don't want to resume specify None
device: cuda:3
vae_beta: 1 #1.2
dimz: 64
num_classes: 16
is_guided: 1
start_epoch: 0
use_aug: 1 #1 # use augmented data, 1 is True, 0 is false
num_augs: 1 #1
burnin_steps: 100
class_weight: 1
chunk_size_test: 50
chunk_size_train: 50
dataset_dir: ../data/
dataset: torchneuromorphic.dvs_gestures.dvsgestures_dataloaders #dvs_gestures_dataloader
return_meta: True # for dvsgesutres, return light and user data
time_shuffle: False # Changed from True by Ni # Shuffle the data being presented in the time.
deltat: 1000
input_shape:
  - 2
  - 128
  - 128
output_shape:
  - 2
  - 128
  - 128
kernel_size:
  - 5
lc_ampl: 0.5
learning_rate:
  - 3.0e-5
  - 3.0e-5
  - 3.0e-5
  - 1.0e-5
learning_method: "bptt"
loss: smoothL1
lr_drop_factor: 1.5
lr_drop_interval: 60
num_epochs: 500
num_conv_layers: 3
num_mlp_layers: 0
num_layers: 3
num_dl_workers: 2
optimizer: adamax
out_channels: 16
online_update: False
pool_size:
  - 2
  - 1
  - 2
  - 1
  - 1
  - 1
random_tau: false
reg_l:
  - .0
  - .0
  - .0
  - .0
stride:
  - 1
  - 1
  - 1
test_interval: 10 #10
